version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./simple-nextjs-app-with-django
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    volumes:
      - ./simple-nextjs-app-with-django:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
